# Generated by Django 4.2.1 on 2023-11-12 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incapacity_management_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidadsalud',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='incapacidad',
            name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='incapacidad',
            name='tipo_entidad',
        ),
        migrations.AddField(
            model_name='entidadsalud',
            name='tipo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incapacity_management_core.tipoentidad'),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='cedula_empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incapacity_management_core.empleado', to_field='cedula'),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='entidad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incapacity_management_core.entidadsalud'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
