# Generated by Django 4.2.1 on 2023-11-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incapacity_management_core', '0003_rename_tipo_id_entidadsalud_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='id_incapacidad',
            new_name='incapacidadId',
        ),
    ]
