# Generated by Django 4.2.1 on 2023-11-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incapacity_management_core', '0004_rename_id_incapacidad_documento_incapacidadid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='incapacidadId',
            new_name='incapacidad',
        ),
        migrations.RenameField(
            model_name='incapacidad',
            old_name='entidad_id',
            new_name='entidad',
        ),
    ]
